import { z } from "zod";

export const shotSchema = z.object({
  projectId: z.string().cuid(),
  sequenceId: z.string().cuid(),
  artistId: z.string().cuid().optional(),
  code: z.string().trim().min(1).optional(),
  shotName: z.string().trim().min(2, "Shot name is required"),
  description: z.string().trim().max(2000).optional(),
  episode: z.string().trim().optional(),
  clientShotName: z.string().trim().optional(),
  clientDeliveryName: z.string().trim().optional(),
  scopeOfWork: z.string().trim().optional(),
  taskTemplate: z.string().trim().optional(),
  status: z.enum([
    "NOT_STARTED",
    "WIP",
    "INTERNAL_REVIEW",
    "CLIENT_REVIEW",
    "APPROVED",
    "DELIVERED",
    "HOLD",
  ]),
  priority: z.coerce.number().int().min(1).max(5).default(3),
  version: z.coerce.number().int().min(1).default(1),
  dueDate: z.string().datetime().optional(),
  vendorETA: z.string().datetime().optional(),
  deliverNextFor: z.string().trim().optional(),
  assignedVendors: z.string().trim().optional(),
  prodTeamComments: z.string().trim().optional(),
  vendorProdComments: z.string().trim().optional(),
  clientAdditionalNotes: z.string().trim().optional(),
  latestClientNote: z.string().trim().optional(),
  flag: z.string().trim().optional(),
  complexity: z.string().trim().optional(),
  clientPriority: z.coerce.number().int().optional(),
  cgComplete: z.boolean().optional(),
  cgSupervisorComments: z.string().trim().optional(),
  cameraInfo: z.string().trim().optional(),
  character: z.string().trim().optional(),
  compositor: z.string().trim().optional(),
  cleanupVendor: z.string().trim().optional(),
  additionalFX: z.string().trim().optional(),
  ascSAT: z.coerce.number().optional(),
  ascSopOffset: z.coerce.number().optional(),
  ascSopPower: z.coerce.number().optional(),
  ascSopSlope: z.coerce.number().optional(),
  allColor: z.boolean().optional(),
  bidId: z.string().trim().optional(),
  bidNotes: z.string().trim().optional(),
  bidProjId: z.string().trim().optional(),
  bidTotal: z.coerce.number().optional(),
  biddingShotCount: z.coerce.number().int().optional(),
  deliveryDateFirstLooks: z.string().datetime().optional(),
  clientWIPDate: z.string().datetime().optional(),
  clientVersionsToFinal: z.coerce.number().int().optional(),
  afterJune2: z.boolean().optional(),
  allowTotal: z.boolean().optional(),
  clientSGId: z.string().trim().optional(),
  clientSGStatus: z.string().trim().optional(),
  clientProdNotes: z.string().trim().optional(),
  clientReportNotes: z.string().trim().optional(),
  clientAdditionalSOW: z.string().trim().optional(),
  clientAdditionalSOWDate: z.string().datetime().optional(),
  contentHubScheduledDelivery: z.string().datetime().optional(),
  contentHubPipelineLink: z.string().trim().optional(),
  assumptions: z.string().trim().optional(),
  bidDays: z.coerce.number().nonnegative().optional(),
  actualDays: z.coerce.number().nonnegative().optional(),
  frameStart: z.coerce.number().int().nonnegative().optional(),
  frameEnd: z.coerce.number().int().nonnegative().optional(),
});

export type ShotSchema = z.infer<typeof shotSchema>;
